---
default_install_hook_types:
    - pre-commit
    - commit-msg

default_stages:
    - commit

repos:
    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v3.0.0
      hooks:
          - id: conventional-pre-commit
            stages: [commit-msg]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: mixed-line-ending
          - id: end-of-file-fixer
          - id: check-json
          - id: check-yaml
            args: [--unsafe]
          - id: check-toml
          - id: debug-statements
          - id: double-quote-string-fixer
          - id: name-tests-test
          - id: requirements-txt-fixer
          - id: check-added-large-files
            args: [--maxkb=1500]

    - repo: https://github.com/psf/black
      rev: 23.12.0
      hooks:
          - id: black
            types:
                - python

    - repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            types:
                - python

    - repo: https://github.com/asottile/setup-cfg-fmt
      rev: v2.5.0
      hooks:
          - id: setup-cfg-fmt


    - repo: https://github.com/asottile/add-trailing-comma
      rev: v3.1.0
      hooks:
          - id: add-trailing-comma

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.15.0
      hooks:
          - id: pyupgrade
            args: [--py38-plus]

    - repo: https://github.com/hhatto/autopep8
      rev: v2.0.4
      hooks:
          - id: autopep8

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.8.0
      hooks:
          - id: mypy
            additional_dependencies: [types-all]

    - repo: https://github.com/myint/docformatter
      rev: v1.7.5
      hooks:
          - id: docformatter

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.21.0  # or higher tag
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1  # or other specific tag
      hooks:
          - id: yamlfmt
